#!/usr/bin/env bash
#
# Squash-merge `dev` into `main`, then recreate `dev` from the updated `main`.
#
# The squash commit message is generated by `claude -p` from the commits being
# squashed (dev..main). Pass an explicit message to override generation.
#
# Usage:
#   scripts/squash-merge-dev-to-main.sh                       # generate via claude -p
#   scripts/squash-merge-dev-to-main.sh "RXR-1234: <message>" # explicit override
#
# The message MUST carry a Jira prefix (RXR-#### or RAD-####) per repo
# commit-hygiene rules; generated messages are validated too.

set -euo pipefail

readonly REMOTE="origin"
readonly MAIN="main"
readonly DEV="dev"
readonly JIRA_PREFIX_RE='^(RXR|RAD)-[0-9]{1,5}: .+'

die() {
  echo "error: $*" >&2
  exit 1
}

[ "$#" -le 1 ] || die "at most one argument: an optional commit-message override"
readonly COMMIT_MSG_OVERRIDE="${1:-}"

# --- Preconditions -----------------------------------------------------------
git rev-parse --is-inside-work-tree >/dev/null 2>&1 \
  || die "not inside a git work tree"

# Working tree and index must be clean so nothing unintended is merged/lost.
if ! git diff --quiet || ! git diff --cached --quiet; then
  die "working tree is dirty; commit or stash changes first"
fi
if [ -n "$(git status --porcelain --untracked-files=all)" ]; then
  die "untracked or modified files present; clean the work tree first"
fi

git remote get-url "$REMOTE" >/dev/null 2>&1 \
  || die "remote '$REMOTE' not found"

git show-ref --verify --quiet "refs/heads/$DEV" \
  || die "local branch '$DEV' does not exist"

# --- Sync both branches with the remote --------------------------------------
echo ">> fetching from $REMOTE"
git fetch --prune "$REMOTE"

echo ">> updating $MAIN"
git checkout "$MAIN"
# Fast-forward only: refuse to proceed if main has diverged from origin/main.
git merge --ff-only "$REMOTE/$MAIN" \
  || die "$MAIN has diverged from $REMOTE/$MAIN; reconcile manually first"

# --- Squash-merge dev into main ----------------------------------------------
echo ">> squash-merging $DEV into $MAIN"
if git merge-base --is-ancestor "$DEV" "$MAIN"; then
  die "$DEV has no commits ahead of $MAIN; nothing to squash"
fi

git merge --squash "$DEV"

# --squash stages changes but does not commit; commit explicitly.
if git diff --cached --quiet; then
  die "squash produced no changes to commit; aborting"
fi

# --- Resolve the commit message ----------------------------------------------
if [ -n "$COMMIT_MSG_OVERRIDE" ]; then
  COMMIT_MSG="$COMMIT_MSG_OVERRIDE"
else
  command -v claude >/dev/null 2>&1 \
    || die "claude CLI not found on PATH; pass an explicit commit message instead"

  echo ">> generating squash commit message with claude -p"
  # Context: subjects/bodies of the squashed commits plus a diffstat.
  commit_log="$(git log "$MAIN..$DEV" --reverse --format='- %s%n%b')"
  diffstat="$(git diff --cached --stat)"

  prompt="Write a single git commit message summarizing the squash-merge of the \
'$DEV' branch into '$MAIN'. Requirements:
- First line MUST start with a Jira prefix in the form 'RXR-1234: ' or 'RAD-1234: ', \
reusing the most frequent Jira ID found in the commits below.
- Keep the subject under 72 characters; add a short body only if it adds value.
- Output ONLY the commit message text. No code fences, no quotes, no commentary.

Squashed commits:
$commit_log

Files changed:
$diffstat"

  COMMIT_MSG="$(printf '%s' "$prompt" | claude -p)"
  # Trim leading/trailing whitespace and surrounding quotes the model may add.
  COMMIT_MSG="$(printf '%s' "$COMMIT_MSG" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's/^"\(.*\)"$/\1/')"

  [ -n "$COMMIT_MSG" ] || die "claude -p returned an empty commit message"
fi

if ! printf '%s' "$COMMIT_MSG" | head -n 1 | grep -Eq "$JIRA_PREFIX_RE"; then
  die "commit message lacks a Jira prefix (e.g. 'RXR-1234: <message>'); got: $(printf '%s' "$COMMIT_MSG" | head -n 1)"
fi

echo ">> commit message:"
printf '%s\n' "$COMMIT_MSG" | sed 's/^/   /'
git commit -m "$COMMIT_MSG"

# --- Recreate dev from the updated main --------------------------------------
echo ">> recreating $DEV from $MAIN"
# Move off dev before deleting it.
git checkout "$MAIN"
git branch -D "$DEV"
git checkout -b "$DEV" "$MAIN"

echo ">> done (local only): $DEV squashed into $MAIN and recreated from $MAIN"
echo ">> nothing pushed; review locally, then push manually when ready"
